[package]
name = "rusty-rays"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rchip8"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
